---
- name: HAPI FHIR Server
  hosts: all
  # become: true
  tags: prep

  tasks:

    - name: Add the OS specific variables
      include_vars:
        file: index.yaml

    - name: Create a hapi directory
      file:
        path: /tmp/hapi-fhir-jpaserver-starter-v{{hapi_ver}}
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes

    # - name: hapi folder exists
    #   stat:
    #     path: /tmp/hapi-fhir-jpaserver-starter-v{{hapi_ver}}
    #   register: stat_result2

    - name: download & unarchive hapi v{{hapi_ver}}
      unarchive:
        src: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/archive/refs/tags/image/v{{hapi_ver}}.tar.gz
        dest: /tmp/hapi-fhir-jpaserver-starter-v{{hapi_ver}}
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: install application.yaml template for hapi jpa Server
      template:
        src: ../application.yaml
        dest: /tmp/hapi-fhir-jpaserver-starter-v{{hapi_ver}}/src/main/resources/application.yaml
        owner: "tomcat"
        group: "tomcat"
        mode: 0755
        force: yes

    - name: Building hapi-fhir (this may take several minutes)
      shell: /opt/maven/bin/mvn clean install --no-transfer-progress --batch-mode package -DskipTests
      args:
        chdir: /tmp/hapi-fhir-jpaserver-starter-v{{hapi_ver}}
      environment:
        MAVEN_OPTS: -Xmx2048m


  # stop tomcat
    - name: stop tomcat
      service: 
        name: tomcat
        state: stopped
      become: true

    # pause to let tomcat stop
    - pause:
        seconds: 10


  # move default ROOT into ROOT-Closed
    - name: move default ROOT into ROOT-Closed
      file:
        path: /opt/tomcat{{tomcat_v_num}}/webapps/ROOT
        state: absent

    - name: move war file to /opt/tomcat{{tomcat_v_num}}/webapps/
      shell: cp ROOT.war /opt/tomcat{{tomcat_v_num}}/webapps/
      args:
        chdir: /tmp/hapi-fhir-jpaserver-starter-v{{hapi_ver}}/target/
      become: true
      

    - name: create lucene target
      ansible.builtin.file:
        path: /opt/tomcat{{tomcat_v_num}}/target
        state: directory
        # needs broad perms
        mode: '0777'
        owner: tomcat
        group: tomcat
      become: true

    - name: create lucenefiles
      ansible.builtin.file:
        path: /opt/tomcat{{tomcat_v_num}}/target/lucenefiles
        state: directory
        mode: '0777'
        owner: tomcat
        group: tomcat
      become: true

    - name: restart tomcat
      systemd:
        name: tomcat
        state: started

    - pause:
        seconds: 10

    - name: status
      command: systemctl status tomcat.service
      register: status


    - debug:
        msg: "{{ status.stdout_lines }}"
