---
- name: Installing supporting packages
  hosts: all
  become: yes

  tasks:

    - name: Updating apt cache
      apt:
        update_cache: yes

    - name: Install basic packages
      apt:
        name: ['git', 'python3-psycopg2']
        state: present

    - name: Install Redis
      apt:
        name: redis-server
        state: present

    - name: Start redis
      service:
        name: redis
        state: started
        enabled: yes

    - name: Download NodeSource setup script
      get_url:
        url: https://deb.nodesource.com/setup_18.x
        dest: /tmp/setup_node.sh

    - name: Execute NodeSource setup script
      command: /bin/bash /tmp/setup_node.sh

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Remove temporary setup script
      file:
        path: /tmp/setup_node.sh
        state: absent

    # - name: Install npm
    #   apt:
    #     name: npm
    #     state: present

    - name: Install fsh-sushi
      shell: |
        npm install -g fsh-sushi