version: '3'

services:

  fhir:
    container_name: fhir
    image: hapiproject/hapi:v5.5.1
    ports:
      - "8080:8080"
    environment:
      profiles.active: r4
      spring.datasource.url: 'jdbc:postgresql://db:5432/hapi'
      spring.datasource.username: "hapi"
      spring.datasource.password: PASS
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.jpa.properties.hibernate.search.enabled: 'true'
      hapi.fhir.tester.home.server_address: "http://localhost:8080/hapi/fhir"
    volumes:
      - hapi-data:/data/hapi
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "PASS"
      POSTGRES_USER: "hapi"
      POSTGRES_DB: "hapi"
    # not needed for networking between containers but here for troubleshooting
    ports:
      - "5432:5432"

volumes:
    hapi-data:
        # external: true