version: '3'

services:

  fhir:
    container_name: fhir
    image: hapiproject/hapi:latest
    ports:
      - "8080:8080"
    environment:
      profiles.active: r4
      spring.datasource.url: 'jdbc:postgresql://db:5432/hapi'
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driverClassName: org.postgresql.Driver
      # - "tester.server_address=http://localhost:8080/fhir"
    volumes:
      - hapi-data:/data/hapi
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    # not needed for networking between containers but here for troubleshooting
    ports:
      - "5432:5432"

volumes:
    hapi-data:
        # external: true