version: '3.7'

services:
  ihris-ui:
    image: ihris-ui:1.0-BETA
    ports:
      - "8080:8080"
    environment:
      UI_CONFIG_FILE: /run/secrets/ui_config
    secrets:
      - ui_config
  ihris-server:
    image: ihris-server:1.0-BETA
    ports:
      - "3000:3000"
    environment:
      SERVER_CONFIG_FILE: /run/secrets/server_config
    secrets:
      - server_config

secrets:
  ui_config:
    file: ./config/ui_config.json
  server_config:
    file: ./config/server_config.json