# Project information
site_name: 'iHRIS V5 Technical Documentation'
site_description: 'Technical documentation for iHRIS V5'
site_author: 'IntraHealth International'
site_url: 'https://github.com/iHRIS/iHRIS'

# Repository
repo_name: 'iHRIS'
repo_url: 'https://github.com/iHRIS'

# Copyright
copyright: 'Copyright &copy; 2020 IntraHealth International'

# Theme
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'blue'
  language: 'en'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.tabs
  # - navigation.expand

nav:
  - Home:
      - 'index.md'
  # - User:
  # - Implementer:
  - Developer:
      - dev/roadmap.md
      - dev/customization.md
      - dev/fhir_http.md
      - dev/modules.md
      - dev/questionnaire.md
      - dev/roles_and_tasks.md
      - dev/short_name.md
      - dev/task_resolution.md
      - dev/todo.md
  - Sysadmin:
      - admin/docker.md
      - admin/install.md
      - admin/config.md
  - User:
      - user/approach.md
      - user/introduction.md
      - user/people.md
      - user/positions.md
      - user/mhero.md
      - user/database.md
      - user/dashboard.md
      - user/locations.md
      - user/audit_logs.md
      - user/reports.md
      - user/system_users.md
      - user/ihris_apps.md
  - FAQs:
      - faq/faq.md
  - Video Tutorials:
      - video/video.md    
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      toc_depth: '3'
  - footnotes

# https://github.com/zhaoterryy/mkdocs-pdf-export-plugin not working
plugins:
  - search
  - git-revision-date-localized
  - mkdocs-video
  # - mknotebooks
  # - pdf-export:
  #     combined: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iHRIS/iHRIS
# theme:
# logo: 'images/logo.png' must be 128x128
# logo:
#   icon: 'menu_book'
