# Project information
site_name: "NHWR v1 Technical Documentation"
site_description: "Technical documentation for NHWR v1"
site_author: "MoH Uganda"
site_url: "https://github.com/jabahum/iHRIS"

# Repository
repo_name: "iHRIS"
repo_url: "https://github.com/jabahum/iHRIS"

# Copyright
copyright: "Copyright &copy; 2022 Moh Uganda"

# Theme
theme:
  name: "material"
  palette:
    primary: "blue grey"
    accent: "indigo"
  language: "en"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - navigation.tabs
  # - navigation.expand

nav:
  - Home:
    - 'index.md'
  # - User:
  # - Implementer:
  - Developer:
    - dev/fhir_http.md
    - dev/modules.md
    - dev/questionnaire.md
    - dev/roles_and_tasks.md
    - dev/short_name.md
    - dev/task_resolution.md
    - dev/todo.md
  - Sysadmin:
    - admin/docker.md
    - admin/install.md
    - admin/config.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      toc_depth : "3"
  - footnotes
  
# https://github.com/zhaoterryy/mkdocs-pdf-export-plugin not working
plugins:
  - search
  - git-revision-date-localized
  # - mknotebooks
  # - pdf-export:
  #     combined: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jabahum/iHRIS


# theme:
# logo: 'images/logo.png' must be 128x128
# logo:
#   icon: 'menu_book'
