---
- name: Installing Apache tomcat{{tomcat_v_num}}
  hosts: all
  tasks:
    - name: Add the OS specific variables
      include_vars:
        file: index.yaml

    - name: Download JDK 17
      get_url:
        url: "https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.rpm"
        dest: "/tmp/jdk-17.rpm"

    - name: Installing JDK 17
      ansible.builtin.yum:
        name: /tmp/jdk-17.rpm
        state: present

    - name: Add tomcat group
      group:
        name: tomcat

    - name: Add "tomcat" user
      user:
        name: tomcat
        group: tomcat
        home: /opt/tomcat{{tomcat_v_num}}
        createhome: no
        system: yes

    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat{{tomcat_v_num}}
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes

    - name: download & unarchive tomcat{{tomcat_v_num}}
      unarchive:
        src: https://archive.apache.org/dist/tomcat/tomcat-{{tomcat_v_num}}/v{{tomcat_ver}}/bin/apache-tomcat-{{tomcat_ver}}.tar.gz
        dest: /opt/tomcat{{tomcat_v_num}}
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat{{tomcat_v_num}}
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Copy tomcat service file
      template:
        src: templates/tomcat.j2
        dest: /etc/init.d/tomcat
      when: ansible_service_mgr == "systemd"

    - name: Create symlink to start/stop/restart tomcat
      file:
        src: /etc/init.d/tomcat
        dest: /etc/rc2.d/S99tomcat
        state: link

    - name: Making tomcat service executable by users
      file:
        path: /etc/init.d/tomcat
        mode: "ugo=x"

    - name: Enable tomcat
      systemd:
        name: tomcat
        state: started
        enabled: yes
      when: ansible_facts['distribution_major_version'] | int > 6

    - name: Enable tomcat
      command: chkconfig tomcat on
      when: ansible_facts['distribution_major_version'] == "6"

    - name: Start tomcat
      service:
        name: tomcat
        state: started
        enabled: yes

    - name: Enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
      when: ansible_service_mgr == "systemd"

    - name: Open tomcat port on the firewall
      firewalld:
        port: 8080/tcp
        permanent: true
        state: enabled
        immediate: yes
      when: ansible_service_mgr == "systemd"

    - name: Set UI access credentials
      template:
        src: tomcat-users.xml.j2
        dest: /opt/tomcat{{tomcat_v_num}}/conf/tomcat-users.xml
      notify: restart tomcat

    - name: Allow access to Manager and Host Manager apps from any IP
      template:
        src: context.xml.j2 
        dest: "{{ item }}"
      with_items:
        - /opt/tomcat{{tomcat_v_num}}/webapps/host-manager/META-INF/context.xml
        - /opt/tomcat{{tomcat_v_num}}/webapps/manager/META-INF/context.xml
      notify: restart tomcat

  handlers:
    - name: restart tomcat
      service:
        name: tomcat
        state: restarted