<template>
  <v-form v-model="detailsForm">
    <v-card-title class="display-1 text-capitalize">
      {{ title }}
    </v-card-title>

    <div v-for="field in schema" v-bind:key="field.label">
      <v-text-field
        :v-model="field.label"
        :label="field.label"
        outline
        :required="field.required"
      ></v-text-field>
    </div>

    <v-flex v-show="showSubsections">
      <div v-for="subsection in subsections" v-bind:key="subsection.label">
        <v-divider class="pb-3" />

        <p class="pl-3 font-weight-bold text-uppercase primary--text">
          Add {{ subsection.label }}
        </p>
      </div>

      <v-divider class="pb-3" />
    </v-flex>
  </v-form>
</template>

<script>
export default {
  data() {
    return {
      detailsForm: true,
      schema: [],
      showSubsections: false,
      subsections: [],
      title: ""
    };
  },
  methods: {
    changeFields(fields, title) {
      const primitiveTypes = [
        "base64Binary",
        "boolean",
        "canonical",
        "code",
        "date",
        "dateTime",
        "decimal",
        "id",
        "instant",
        "markdown",
        "oid",
        "positiveInt",
        "string",
        "time",
        "unsignedInt",
        "uri",
        "url",
        "uuid"
      ];

      let schema = [];
      let showSubsections = false;
      let subsections = [];

      fields.forEach(function(field) {
        // skip id, this will be autogenerated
        if (field.name != "id") {
          // check for primitive types
          if (primitiveTypes.indexOf(field.type) !== -1) {
            schema.push({
              label: field.name,
              required: field.required
            });
          } else {
            showSubsections = true;
            subsections.push({
              label: field.name,
              definition: field.type
            });
          }
        }
      });

      this.schema = schema;
      this.showSubsections = showSubsections;
      this.subsections = subsections;
      this.title = title;
    }
  }
};
</script>
